
package kps.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "KPSPublic", targetNamespace = "http://tckimlik.nvi.gov.tr/WS", wsdlLocation = "file:/C:/java/tobeto/workspace/KPSDeneme/src/main/resources/KPSPublic.xml")
public class KPSPublic
    extends Service
{

    private static final URL KPSPUBLIC_WSDL_LOCATION;
    private static final WebServiceException KPSPUBLIC_EXCEPTION;
    private static final QName KPSPUBLIC_QNAME = new QName("http://tckimlik.nvi.gov.tr/WS", "KPSPublic");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/java/tobeto/workspace/KPSDeneme/src/main/resources/KPSPublic.xml");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        KPSPUBLIC_WSDL_LOCATION = url;
        KPSPUBLIC_EXCEPTION = e;
    }

    public KPSPublic() {
        super(__getWsdlLocation(), KPSPUBLIC_QNAME);
    }

    public KPSPublic(WebServiceFeature... features) {
        super(__getWsdlLocation(), KPSPUBLIC_QNAME, features);
    }

    public KPSPublic(URL wsdlLocation) {
        super(wsdlLocation, KPSPUBLIC_QNAME);
    }

    public KPSPublic(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, KPSPUBLIC_QNAME, features);
    }

    public KPSPublic(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public KPSPublic(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns KPSPublicSoap
     */
    @WebEndpoint(name = "KPSPublicSoap")
    public KPSPublicSoap getKPSPublicSoap() {
        return super.getPort(new QName("http://tckimlik.nvi.gov.tr/WS", "KPSPublicSoap"), KPSPublicSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns KPSPublicSoap
     */
    @WebEndpoint(name = "KPSPublicSoap")
    public KPSPublicSoap getKPSPublicSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tckimlik.nvi.gov.tr/WS", "KPSPublicSoap"), KPSPublicSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (KPSPUBLIC_EXCEPTION!= null) {
            throw KPSPUBLIC_EXCEPTION;
        }
        return KPSPUBLIC_WSDL_LOCATION;
    }

}
